### ISSUE TITLE
Y coordinate probably off

### ISSUE THREAD

**Issue by thomasrudin** [thomasrudin-mt/minetest-tile-server#13]
https://pandorabox.io/forum/discussion/26/on-site-map-shows-wrong-coords-in-command-line#latest

**Comment by bvs23bkv33** [comment]
i'm barsik :) i'm registered here

**Comment by thomasrudin** [comment]
Hi barsik, i did test that but it works for me... what browser do you use?

**Comment by thomasrudin** [comment]
fixed with: 94488364571e6e5095d2ac781c6bd79b28cef109
