### ISSUE TITLE
Is this suppose to be hardcoded?

### ISSUE THREAD

**Issue by Ryan-Nolan** [thomasrudin-mt/minetest-tile-server#39]
Unless i'm mistaken, should this not be configurable from the config?

https://github.com/thomasrudin-mt/minetest-tile-server/blob/783f76186035fcebfb84b5d6c8fd81d1da2a1a3d/proxy.js#L9

**Comment by thomasrudin** [comment]
uhm, not really, i used that for remote development, maybe i should remove that completely...

**Comment by Ryan-Nolan** [comment]
Java isn't really my strength, so if I'm being honest i had no idea whether it was included in the source of the production version. If it doesn't affect end users don't worry about it. I just brought it up in case it was something that got missed. :)

**Comment by thomasrudin** [comment]
fixed with 8b9f7e677c2306c7be27a3c9273a656c810b16b3

**Comment by thomasrudin** [comment]
Document in #44
