### ISSUE TITLE
colors.txt

### ISSUE THREAD

**Issue by Ryan-Nolan** [thomasrudin-mt/minetest-tile-server#40]
Would it be possible to have the tile server read a colors.txt file on startup rather than on compile, Maybe have a config option that allows us to define the location of the colors.txt file.

Also is it possible to apply alpha channels to the colors.txt file?

**Comment by thomasrudin** [comment]
strange, i thought i made an option for that but i can't find it now :(

**Comment by thomasrudin** [comment]
sadly no, thats in the classpath: the jar/zip file its packed in (tileserver.jar) one possibility right now would to untip that file, make changes to the bundled colors.txt and re-pack/zip it again...
Until that is implemented anyway, thats a must-have i think...
